apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basket
spec:
  template:
    metadata:
      labels:
        app: aksworkshop
        component: basket
    spec:
      containers:
      - name: basket
        image: gabrielgt.azurecr.io/basket
        imagePullPolicy: Always
        env:
        - name: constr
          value: mongodb://10.240.0.67
        - name: PATH_BASE
          value: /basket-api
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
      imagePullSecrets:
      - name: acr-gabriel-key
      tolerations:
        - key: virtual-kubelet.io/provider
          value: azure
          effect: NoSchedule
      nodeSelector:
        type: virtual-kubelet

