apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog
spec:
  template:
    metadata:
      labels:
        app: aksworkshop
        component: catalog
    spec:
      containers:
      - name: catalog
        image: gabrielgt.azurecr.io/catalog
        imagePullPolicy: Always
        env:
        - name: constr
          valueFrom:
              configMapKeyRef:
                key: constr
                name: cm-catalog
        - name: PATH_BASE
          value: /catalog-api
        ports:
        - containerPort: 80
        livenessProbe:
            httpGet:
              path: /liveness
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
            successThreshold: 1
            initialDelaySeconds: 5
        readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 60
            successThreshold: 2
      imagePullSecrets:
      - name: acr-gabriel-key
