apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: e459a3cd7007403ea9a5.northeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: website
          servicePort: http
        path: /
      - backend:
          serviceName: basket
          servicePort: http
        path: /basket-api
  tls:
    - hosts:
      - e459a3cd7007403ea9a5.northeurope.aksapp.io
      secretName: gabriel-crt-secret


